site_name: Unified Phenotype Ontology
theme: readthedocs
nav:
  - Getting started: index.md
  - Cite: cite.md
  - About uPheno: about.md
  - uPheno community effort:
      - Meetings: organization/meetings.md
      - Outreach: organization/outreach.md
  - How-to guides:
      - Standard ODK workflows:
          - Overview: odk-workflows/index.md
          - Editors Workflow: odk-workflows/EditorsWorkflow.md
          - Release Workflow: odk-workflows/ReleaseWorkflow.md
          - Manage your ODK Repository: odk-workflows/RepoManagement.md
          - Your ODK Repository Overview: odk-workflows/RepositoryFileStructure.md
          - Setting up Docker for ODK: odk-workflows/SettingUpDockerForODK.md
          - Manage imports: odk-workflows/UpdateImports.md
          - Manage documentation: odk-workflows/ManageDocumentation.md
          - Manage Continuous Integration: odk-workflows/ContinuousIntegration.md
          - Manage automated tests: odk-workflows/ManageAutomatedTest.md
          - Overview of components: odk-workflows/components.md
      - Contributing: contributing.md
      - Advanced Phenotype Ontology Editor workflows:
          - How to run a uPheno 2 release: howto/run-upheno2-release.md
          - How to set up s3 for uploading upheno data files: howto/set-up-s3.md
          - Add custom uPheno Makefile: howto/custom-upheno-makefile.md
          - Add the uPheno direct relation extension: howto/add-relation-extension.md
          - Pattern merge - replace workflow: howto/pattern-merge-replace-workflow.md
          - Phenotype Ontology Editors' Workflow: howto/editors_workflow.md
  - Tutorials:
      - Using uPheno in Data Analysis: tutorials/analysis.md
      - Using uPheno in Curation: tutorials/curation.md
      - Using uPheno for Grouping Data: tutorials/grouping.md
  - Reference:
    - Core concepts: reference/core_concepts.md
    - EQ modelling:
      - Overview of EQ modelling: reference/eq.md
      - Abnormal phenotypes: reference/modelling/abnormal.md 
      - Absence modelling: reference/modelling/absence.md
    - The Phenotype Reconciliation Effort: reference/reconciliation_effort.md
    - Use Cases: reference/use_cases.md
    - Components:
      - Overview: reference/components.md
      - Drosophila Phenotype Ontology: reference/components/dpo.md
      - Fission Yeast Phenotype Ontology: reference/components/fypo.md
      - Human Phenotype Ontology: reference/components/hp.md
      - Mammalian Phenotype Ontology: reference/components/mp.md
      - C. elegans Phenotype Ontology: reference/components/wbphenotype.md
      - Zebrafish Phenotype Ontology: reference/components/zp.md
    - Aligning with other ontologies:
      - Overview: reference/phenotype-ontology-alignment.md
    - Imports:
      - Overview: reference/imports.md
      - Gene Ontology: reference/imports/go.md
      - Uberon: reference/imports/uberon.md
      - PATO: reference/imports/pato.md
    - Mappings:
      - Overview: reference/mappings.md
      - MP-HP: reference/mappings/mp_hp.md
    - Quality Control:
      - Overview: reference/qc.md
      - Standard OBO checks: reference/qc/odk_checks.md
    - Design Patterns:
      - Design Patterns Overview: reference/patterns.md
  - Other Monarch Docs: https://monarch-initiative.github.io/monarch-documentation/
  
